[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*.md"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"

[[headers]]
  for = "/seed/*.md"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"
